# This compose file is used to create a multi-container app with a container running the
# javascript api, and a container with a database to be accessed by the api

services:

  api:
    build:
      context: ../verademo-javascript-api/
      dockerfile: ../verademo-app-docker/docker/Dockerfile-NodeJS
    ports: 
      - "8000:8000"
    depends_on:
      - db
    develop:
      watch:
        - path: package.json
          action: rebuild
        - path: ../verademo-javascript-api/
          target: /user/src/app
          action: sync

  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'blab'
      MYSQL_USER: 'blab'
      MYSQL_PASSWORD: 'z2^E6J4$$;u;d'
    ports:
      - 3306:3306
    
